# Generated by Django 2.0.8 on 2018-09-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikelnummer',
            fields=[
                ('artikelnummer', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('artikelbezeichnung', models.CharField(max_length=100)),
            ],
        ),
    ]
