# Generated by Django 2.0.8 on 2018-09-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artikelnummer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezeptur',
            fields=[
                ('rezeptnummer', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rezeptbezeichnung', models.CharField(max_length=100)),
            ],
        ),
    ]
